import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import dayjs, { Dayjs } from 'dayjs';

import { Box, Typography } from '@mui/material';

import { IWeeklyMenuWithId } from '../models/weekly-menu.model';
import { getWeeklyMenuByDate } from '../mongodb/db-weekly-menu';
import WeeklyMenu from '../components/menus/weekly-menu';
import WeekPicker from '../components/ui/week-picker';

type HomePageProps = {
  currentWeeklyMenu?: IWeeklyMenuWithId;
};

export default function Home(props: HomePageProps) {
  const { currentWeeklyMenu } = props;

  const [weeklyMenu, setWeeklyMenu] = useState(currentWeeklyMenu);
  const [displayWeekStart, setDisplayWeekStart] = useState(
    dayjs(weeklyMenu?.weekStartDate).startOf('week')
  );
  const [isCreateMode, setIsCreateMode] = useState(false);

  // const weekStart = dayjs(weeklyMenu?.weekStartDate).startOf('week');
  const weekEnd = displayWeekStart.endOf('week');
  const displayFormat = 'ddd, MMM DD';

  const createMenuHandler = () => {
    console.log('in createMenuHandler');

    setIsCreateMode(true);
  };

  const onWeekChange = async (newWeek: Dayjs) => {
    const response = await fetch(
      `/api/weekly-menus?date=${newWeek.format('YYYY-MM-DD')}`
    );

    if (response.ok) {
      const body = await response.json();

      const menu: IWeeklyMenuWithId = body.weeklyMenu;

      setWeeklyMenu(menu);
    } else {
      setWeeklyMenu(undefined);
    }

    setDisplayWeekStart(newWeek);
    setIsCreateMode(false);
  };

  let content: JSX.Element = (
    <>
      It looks like you have no menu for this week
      <button onClick={createMenuHandler}>Create weekly menu</button>
    </>
  );

  if (weeklyMenu) {
    content = (
      <WeeklyMenu
        weekStart={displayWeekStart.format('YYYY-MM-DD')}
        weeklyMenu={weeklyMenu}
      />
    );
  } else if (isCreateMode) {
    content = <WeeklyMenu weekStart={displayWeekStart.format('YYYY-MM-DD')} />;
  }

  return (
    <>
      <Head>
        <title>Menu Helper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <Box>
          <WeekPicker onWeekChange={onWeekChange} />
          <Typography>
            {displayWeekStart.format(displayFormat)} -{' '}
            {weekEnd.format(displayFormat)}
          </Typography>
          {content}
        </Box>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const currentWeekStartString = dayjs().startOf('week').format('YY-MM-DD');
  const currentWeeklyMenu = await getWeeklyMenuByDate(currentWeekStartString);
  const staticReturn: { props: any; revalidate: false | number } = {
    props: {
      latestWeeklyMenu: currentWeeklyMenu,
    },
    revalidate: false,
  };

  if (currentWeeklyMenu) {
    staticReturn.revalidate = 86400;
  }

  return staticReturn;
};
